apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app: web-server
    tier: web-server
spec:
  ports:
    # the port that this service should serve on
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: web-server
    tier: web-server
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
        tier: web-server
    spec:
      containers:
      - name: web-server
        image: peihsinsu/simpleweb
        ports:
        - containerPort: 3000
        env:
        - name: PORT 
          value: "3000"
        - name: NODE_ENV
          value: production
        - name: GET_HOSTS_FROM
          value: dns
